import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import MessageOperations from './components/MessageOperations';

import Navbar from './components/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/create-message">
        <button className="bg-blue-400 hover:bg-blue-300 shadow p-2 rounded fixed bottom-10 text-white right-10">
          Leave a message
        </button>
      </Link>
    </>
  );
}
